### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by vbonluk** [AlayshChen/WeChatPlugin#1]
cp: /Applications/WeChat.app/Contents/MacOS/WeChat_: Permission denied
cp: /Users/Vbon/Library/Developer/Xcode/DerivedData/WeChatPlugin-ffaaaihxygikyrdvcrurztvdckpz/Build/Products/Debug/MacWeChatTimeLinePlugin.framework: No such file or directory
/Users/Vbon/Library/Developer/Xcode/DerivedData/WeChatPlugin-ffaaaihxygikyrdvcrurztvdckpz/Build/Intermediates/WeChatPlugin.build/Debug/WeChatPlugin.build/Script-8BFD11B01E8CC300004077B3.sh: line 15: insert_dylib: command not found

**Comment by AlayshChen** [comment]
It seem that you don't clone this project. But If you like to use you project, please repair the permission of MacOS directory and install insert_dylib.

**Comment by vbonluk** [comment]
I run successfully,but it crash when I click timeline.
error log:
2017-03-30 13:01:07.688263 WeChat[67349:16884287] 
-[MMTimeLineMainViewController listTableViewDataSource]: unrecognized selector sent to instance 0x104858080

**Comment by vbonluk** [comment]
Is something I forget to add ? I have already execute “pod install”

**Comment by AlayshChen** [comment]
What is the version of WeChat.app ? Try to update it.

**Comment by vbonluk** [comment]
![qq20170330-131629](https://cloud.githubusercontent.com/assets/7578155/24488678/2371bd14-154b-11e7-980e-c0daceab3c48.png)

**Comment by AlayshChen** [comment]
The plugin support for 2.2.0 and 2.2.1 version.

**Comment by vbonluk** [comment]
It work！,very awsome

**Comment by Easyzhan** [comment]
Failed to connect (settingButton) outlet from (MMMainViewController) to (NSButton): missing setter or instance variable
2017-04-01 21:56:50.190 WeChat[3396:126764] +[NSButton buttonWithImage:target:action:]: unrecognized selector sent to class 0x7fff7807c368

2.2.1
